meta_product_name: "Friendlendar"
meta_title: "Friendlendar - Stay connected with your friends"
meta_description: "Wanna meet your friends but you never know their availability? Join Friendledar. Find the most convenient time to meet up"
meta_image: "F-logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
